name: Check & get new version of HoloCure from itch.io
on:
  schedule:
    - cron:  '0 0 * * *'
    - cron:  '0 12 * * *'

  workflow_dispatch:

jobs:
  get_version:
    name: Get latest HoloCure version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run script for update
        run: |
          npm i
          node .github/workflows/itchio.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update new HoloCure version
