name: Get latest HoloCure
on:
#   schedule:
#     - cron:  '0 0 * * *'
#     - cron:  '0 12 * * *'

  workflow_dispatch:

jobs:
  get_latest_holocure:
    name: Get latest HoloCure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run script for update
        run: |
          npm i
          node .github/workflows/itchio.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update new HoloCure version
